language: bash
dist: xenial

before_install:
- sudo chmod u+x .travis/*.sh
- /bin/bash .travis/setup.sh

script:
#- /bin/bash .travis/build.sh Singularity
# build 
#- travis_wait 40 sudo singularity build Singularity.simg Singularity
- sudo singularity build Singularity.simg Singularity
# 
# test and push
- if [ "$TRAVIS_BRANCH" = "master" ] && [ "$TRAVIS_PULL_REQUEST" = "false" ]; then
   echo "depoly"; else /bin/bash .travis/test.sh; fi

